### ISSUE TITLE
Ar fi benefic daca s-ar putea citi mai multe contoare

### ISSUE THREAD

**Issue by samuellazea** [cnecrea/e-bloc#1]
Buna,

vreau sa specific de la bun inceput ca acesta nu este o problema ci mai degraba un feature request.
Configurand componentul la index contoare el ia doar un contor. In contul meu eu am 4 contoare care ar fi super daca le-as putea vedea pe toate. Ma gandeam la un loop peste contoare si sa iau datele de la fiecare contor.

Contoarele mele arata asa la ora actuala

`
 {
    "1": {
        "status": "ok",
        "id_ap": "0",
        "id_contor": "0",
        "tip": "0",
        "titlu": "",
        "index_vechi": "0",
        "index_nou": "0",
        "flag": "0",
        "data": "",
        "flag_contor": "0",
        "guid": ""
    },
    "2": {
        "status": "ok",
        "id_ap": "159",
        "id_contor": "321995",
        "tip": "1",
        "titlu": "AR ",
        "index_vechi": "79344",
        "index_nou": "80258",
        "flag": "18",
        "data": "2024-12-30",
        "flag_contor": "124",
        "guid": ""
    },
    "3": {
        "status": "ok",
        "id_ap": "159",
        "id_contor": "321996",
        "tip": "2",
        "titlu": "AC ",
        "index_vechi": "49406",
        "index_nou": "49906",
        "flag": "18",
        "data": "2024-12-30",
        "flag_contor": "92",
        "guid": ""
    },
    "4": {
        "status": "ok",
        "id_ap": "159",
        "id_contor": "3879318",
        "tip": "16",
        "titlu": "Căldură ",
        "index_vechi": "4866300",
        "index_nou": "4927500",
        "flag": "18",
        "data": "2024-12-30",
        "flag_contor": "68",
        "guid": ""
    },
    "5": {
        "status": "ok",
        "id_ap": "159",
        "id_contor": "5862",
        "tip": "32",
        "titlu": "Energie",
        "index_vechi": "9796500",
        "index_nou": "9837600",
        "flag": "18",
        "data": "2024-12-30",
        "flag_contor": "92",
        "guid": ""
    }
 }
`

Ar fi fain daca as putea avea fiecare contor cu parte din titlu citit din obiect. De asemenea apa calda, rece si caldura cantitatea este in mc dar la Energie este in kwh.

Eu am incercat ceva de genul dar ceva nu fac cum trebuie si nu le pot avea pe toate

`
class EBlocContoareSensor(EBlocSensorBase):
    """Senzor pentru `AjaxGetIndexContoare.php`."""

    def __init__(self, coordinator):
        super().__init__(coordinator, "Index contor")

    async def async_update(self):
        """Actualizează datele pentru senzorii `index`."""
        data = self._coordinator.data.get("index", {})
        
        index_list = []
        attributes = {}

        for key, meter_data in data.items():
            titlu = meter_data.get("titlu", "").strip()
            index_vechi = meter_data.get("index_vechi", "").strip()
            index_nou = meter_data.get("index_nou", "").strip()

            if not titlu or not index_vechi or not index_nou:
                continue

            try:
                index_vechi = f"{int(float(index_vechi) // 1000)}" if index_vechi else "Necunoscut"
            except ValueError:
                index_vechi = "Necunoscut"

            try:
                index_nou = f"{int(float(index_nou) // 1000)}" if index_nou else "Necunoscut"
            except ValueError:
                index_nou = "Necunoscut"

            index_list.append(f"{titlu} - {index_vechi} mc")
            attributes[f"Index vechi {titlu}"] = f"{index_vechi} mc" if index_vechi != "Necunoscut" else "Necunoscut"
            attributes[f"Index nou {titlu}"] = f"{index_nou} mc" if index_nou != "Necunoscut" else ""

        if index_list:
            self._attr_state = " / ".join(index_list)
        else:
            self._attr_state = "Necunoscut"

        self._attr_extra_state_attributes = attributes

    @property
    def unique_id(self):
        return f"{DOMAIN}_contor"

    @property
    def name(self):
        return self._attr_name

    @property
    def state(self):
        return self._attr_state

    @property
    def extra_state_attributes(self):
        return self._attr_extra_state_attributes

    @property
    def icon(self):
        """Pictograma senzorului."""
        return "mdi:counter"`
        
Poate mi-ai putea da un indiciu ce nu fac bine si dupa ce il am si merge poate fac un pull request daca vrei sa il adaugi in componenta.
      
Multumesc frumos pentru munca ta. Chiar e apreciata

**Comment by cnecrea** [comment]
salut, aplicatia nu este 100% functionala. Este inca in teste.

**Comment by samuellazea** [comment]
Am inteles si nu incerc sa presez. Incerc doar sa te ajut daca pot sau macar daca e putin cu partea de testare daca vrei :)

**Comment by cnecrea** [comment]
> Am inteles si nu incerc sa presez. Incerc doar sa te ajut daca pot sau macar daca e putin cu partea de testare daca vrei :)

Apreciez! În momentul de față, lucrez la o actualizare pentru E-ON România și, în același timp, dezvolt MyElectrica. Recunosc, mă prinde puțin pe picior greșit. Ce pot să spun este că, după ce termin cu MyElectrica, o să mă uit și la E-Bloc să vedem ce putem îmbunătăți. Cel mai probabil, voi lua totul de la zero pentru a face lucrurile cât mai bine. 😊

**Comment by samuellazea** [comment]
Super. Daca te pot ajuta cu ceva sa ma anunti si iti dau un discord sau ceva si putem vorbi mai usor. Oricum ai facut treaba faina. Multumesc pentru ce ai facut

**Comment by cnecrea** [comment]
> Super. Daca te pot ajuta cu ceva sa ma anunti si iti dau un discord sau ceva si putem vorbi mai usor. Oricum ai facut treaba faina. Multumesc pentru ce ai facut

Iti multumesc, discutam pe viitor
